#!/usr/bin/env python3
"""
vasp_utils.py
VASP 输入文件生成与 OUTCAR 解析工具库

提供：
- INCAR 生成（体相/表面/空位/间隙 四种场景，ISIF 与 EDIFF 自动区分）
- KPOINTS 生成
- MAGMOM 自动生成（AFM 层序 + 掺杂位次）
- OUTCAR 关键指标提取（能量、力、收敛状态、自旋密度）
"""

from __future__ import annotations

import os
import re
from typing import List, Optional

import numpy as np
from pymatgen.core import Structure

# 论文参数
ENCUT = 650
U_EFF = 4.0
U_U = 4.5
J_U = 0.5


def write_incar(output_dir: str, system: str, calc_type: str = "surface_sto",
                n_ions: int = 96, magmoms: Optional[List[float]] = None,
                species_order: Optional[List[str]] = None,
                add_dftu_dopant: bool = False) -> str:
    """
    生成 INCAR 文件。

    calc_type:
      - "bulk":        体相, ISIF=3, EDIFF=1E-7, EDIFFG=-0.01
      - "surface_sto": 化学计量比表面（纯 UO2 用 ISIF=3；MOX 用 ISIF=2）
      - "surface_substo": 空位/间隙表面, ISIF=2, EDIFF=1E-7
    """
    os.makedirs(output_dir, exist_ok=True)

    if calc_type == "bulk":
        isif = 3
        ediff = "1E-7"
        ediffg = "-0.01"
    elif calc_type == "surface_sto":
        isif = 3 if "pure" in system else 2
        ediff = "1E-6"
        ediffg = "-0.02"
    elif calc_type == "surface_substo":
        isif = 2
        ediff = "1E-7"
        ediffg = "-0.02"
    else:
        raise ValueError(f"unknown calc_type: {calc_type}")

    # DFT+U: U 的 f 轨道 (l=3), 其他默认 -1
    n_species = len(species_order) if species_order else 2
    ldaul = ["3"] + ["-1"] * (n_species - 1)
    ldauu = [str(U_U)] + ["0.0"] * (n_species - 1)
    ldauj = [str(J_U)] + ["0.0"] * (n_species - 1)

    # 掺杂元素 d 轨道 +U（敏感性测试用）
    if add_dftu_dopant and species_order:
        for i, sp in enumerate(species_order):
            if sp in ("Mo", "Nb"):
                ldaul[i] = "2"
                ldauu[i] = "2.0"
                ldauj[i] = "0.5"

    if magmoms is None:
        magmom_line = ""
    else:
        # 压缩为 N*v 形式
        parts = []
        i = 0
        while i < len(magmoms):
            j = i
            while j < len(magmoms) and abs(magmoms[j] - magmoms[i]) < 1e-6:
                j += 1
            parts.append(f"{j-i}*{magmoms[i]:.2f}")
            i = j
        magmom_line = f"MAGMOM  = {' '.join(parts)}"

    content = f"""# ============================================================
# VASP INCAR -- generated by vasp_utils.py
# SYSTEM = {system}
# calc_type = {calc_type}
# ============================================================
SYSTEM  = {system}
PREC    = Accurate
ENCUT   = {ENCUT}
EDIFF   = {ediff}
EDIFFG  = {ediffg}
ISMEAR  = 0
SIGMA   = 0.05
LREAL   = .FALSE.

# --- DFT+U (Dudarev) ---
LDAU      = .TRUE.
LDAUTYPE  = 2
LDAUL     = {' '.join(ldaul)}
LDAUU     = {' '.join(ldauu)}
LDAUJ     = {' '.join(ldauj)}
LMAXMIX   = 4

# --- Magnetism (collinear AFM) ---
ISPIN   = 2
{magmom_line}

# --- Ionic relaxation ---
NSW     = 200
IBRION  = 2
ISIF    = {isif}

# --- Parallel ---
NCORE   = 8

# --- Output ---
LWAVE   = .TRUE.
LCHARG  = .TRUE.
LORBIT  = 11
"""
    path = os.path.join(output_dir, "INCAR")
    with open(path, "w") as f:
        f.write(content)
    return path


def write_kpoints(output_dir: str, mesh: tuple = (5, 5, 1)) -> str:
    """生成 KPOINTS（Monkhorst-Pack）."""
    os.makedirs(output_dir, exist_ok=True)
    content = f"""Automatic mesh
0
Monkhorst-Pack
{mesh[0]}  {mesh[1]}  {mesh[2]}
0  0  0
"""
    path = os.path.join(output_dir, "KPOINTS")
    with open(path, "w") as f:
        f.write(content)
    return path


def write_poscar(structure: Structure, output_dir: str) -> str:
    """写入 POSCAR."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "POSCAR")
    structure.to(fmt="poscar", filename=path)
    return path


def build_magmoms(structure: Structure, layer_signs=None) -> List[float]:
    """
    为 UO2 6 层 slab 自动生成 AFM 磁矩：
    奇数层(1,3,5) +2.0，偶数层(2,4,6) -2.0，O 与掺杂位默认 0.0。

    layer_signs: 可选，自定义每层符号，如 [1,-1,1,-1,1,-1]
    """
    from structure_utils import assign_layers

    layers = assign_layers(structure, axis=2)
    n = len(structure)
    mag = np.zeros(n)
    if layer_signs is None:
        layer_signs = [1, -1, 1, -1, 1, -1]
    for li, idx_list in layers.items():
        if li < len(layer_signs):
            for idx in idx_list:
                if str(structure[idx].specie) == "U":
                    mag[idx] = 2.0 * layer_signs[li]
    return mag.tolist()


# ============================================================
# OUTCAR 解析
# ============================================================

def read_energy(outcar: str) -> Optional[float]:
    """读取 OUTCAR 末步自由能 (eV)."""
    if not os.path.exists(outcar):
        return None
    vals = []
    with open(outcar) as f:
        for line in f:
            if "free  energy" in line:
                m = re.search(r"free  energy\s*=\s*([-\d.]+)", line)
                if m:
                    vals.append(float(m.group(1)))
    return vals[-1] if vals else None


def read_max_force(outcar: str) -> Optional[float]:
    """读取 OUTCAR 末步 TOTAL-FORCE 最大力分量 (eV/Ang)."""
    if not os.path.exists(outcar):
        return None
    blocks = []
    current = []
    with open(outcar) as f:
        for line in f:
            if "TOTAL-FORCE" in line:
                if current:
                    blocks.append(current)
                current = []
            elif current is not None:
                m = re.match(r"\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)", line)
                if m:
                    current.append([float(x) for x in m.groups()])
    if not blocks:
        return None
    last = blocks[-1]
    if not last:
        return None
    return max(abs(row[3]) for row in last)


def is_converged(outcar: str) -> bool:
    """检查 OUTCAR 是否达到电子步收敛."""
    if not os.path.exists(outcar):
        return False
    with open(outcar) as f:
        for line in f:
            if "reached required accuracy" in line:
                return True
    return False


def is_failed(outcar: str) -> bool:
    if not os.path.exists(outcar):
        return False
    with open(outcar) as f:
        for line in f:
            if "aborting loop" in line or "Error" in line and "ERROR" in line.upper():
                return True
    return False


def read_spin_densities_from_osziacar(oszicar) -> Optional[list]:
    """从 OSZICAR 末步读取逐原子磁矩（需 ISPIN=2 且打印瞬时磁矩）."""
    raise NotImplementedError("逐原子自旋密度请用 PARCHG/CHGCAR 积分，或用 vaspkit/其他工具；"
                              "OSZICAR 只含总磁矩。")


def extract_atomic_spin_from_vasprun(vasprun_xml: str) -> dict:
    """
    从 vasprun.xml 提取逐原子磁矩（自旋密度近似）。
    返回 {species: [spin, spin, ...]}。需 VASP 计算含 ISPIN=2。
    """
    import xml.etree.ElementTree as ET

    tree = ET.parse(vasprun_xml)
    root = tree.getroot()
    atoms = root.find("atominfo/atoms")
    n_atoms = int(atoms.text.strip())
    species = [s.text.strip() for s in root.find("atominfo/array[@name='atomtypes']").find("set")][::5]
    # 解析 magnetization 数组（最后一条）
    mag_nodes = root.findall("calculation")
    mag = None
    for calc in mag_nodes:
        node = calc.find("eigenvalues")
        node2 = calc.find("partial")
        _ = (node, node2)
    # 简化实现：从 final ionic step 的 /calculation/array name=magnetization
    final_calc = mag_nodes[-1]
    mag_arrays = final_calc.find("array[@name='magnetization']/set/r")
    if mag_arrays is None:
        return {}
    spins = []
    for row in list(mag_arrays)[-n_atoms:]:
        spins.append(float(row.text.split()[-1]))
    return {"species_order": species, "spins": spins}
